forge 'https://forge.puppet.com'
mod 'garethr-kubernetes', '0.6.0'
mod 'puppetlabs/inifile', '3.0.0'
mod 'puppetlabs/stdlib',  '6.0.0'
mod 'puppetlabs/concat',  '6.0.0'
mod 'puppetlabs-apache', '6.0.0'
mod 'puppetlabs-firewall', '3.0.0'
